const Data = [
  {
    id: 1,
    name: "Japan",
    info: "Japan is a fascinating country where tradition meets technology. Visitors are drawn to its cherry blossoms, ancient temples, and modern cities like Tokyo and Osaka. From serene Zen gardens and tea ceremonies to neon-lit streets and high-speed trains, Japan offers a unique experience that feels like stepping into two different worlds.",
    image: "/image/japan.jpg",
    price: "99,999",
  },
  {
    id: 2,
    name: "Bali",
    info: "ali is a tropical paradise that attracts travelers with its pristine beaches, lush rice terraces, vibrant nightlife, and ancient temples. Known for yoga retreats and cultural experiences, Bali offers a mix of relaxation and adventure, from surfing to exploring spiritual sites like Uluwatu and Tanah Lot.",
    image: "/image/bali.jpg",
    price: "99,999",
  },
  {
    id: 3,
    name: "Europe",
    info: "Europe is a dream destination for travelers, offering a rich blend of history, art, and culture. From the romantic streets of Paris and Rome to the breathtaking landscapes of the Swiss Alps and Mediterranean coast, Europe has something for everyone. Castles, cathedrals, and vibrant cities make it a timeless journey.",
    image: "/image/Europe.jpg",
    price: "99,999",
  },
  {
    id: 4,
    name: "Kerala-India",
    info: "Kerala, often called “God’s Own Country,” is a lush green paradise in southern India. Famous for its backwaters, houseboats, tea plantations, and Ayurvedic wellness, Kerala is perfect for nature lovers and those seeking peace. From wildlife sanctuaries to Kathakali dance performances, it offers a mix of culture, relaxation, and scenic beauty.",
    image: "/image/Kerala.jpg",
    price: "99,999",
  },
  {
    id: 5,
    name: "Mumbai-India",
    info: "Mumbai is India’s bustling financial and entertainment capital, also known as the “City of Dreams.” It is home to Bollywood, Marine Drive, the Gateway of India, and vibrant street food culture. A city that never sleeps, Mumbai offers both modern skyscrapers and colonial charm, making it a must-visit for travelers seeking energy and diversity.",
    image: "/image/mumbai.jpg",
    price: "99,999",
  },
  {
    id: 6,
    name: "Nepal",
    info: "Nepal is a haven for adventure and spirituality. Nestled in the Himalayas, it is home to Mount Everest and countless trekking routes that attract hikers from across the world. Beyond adventure, Nepal offers ancient temples, Buddhist monasteries, and warm hospitality. A trip here is both a spiritual and natural retreat for the soul.",
    image: "/image/Nepal.jpg",
    price: "99,999",
  },
  {
    id: 7,
    name: "Singapore",
    info: "Singapore is a futuristic city-state known for its modern architecture, world-class shopping, and cultural diversity. From Marina Bay Sands and Gardens by the Bay to vibrant Chinatown and Little India, the city offers an unforgettable urban experience. Its cleanliness, safety, and unique mix of nature and innovation make it perfect for all",
    image: "/image/singapore.jpg",
    price: "99,999",
  },
  {
    id: 8,
    name: "Spiritual Destination",
    info: "Spiritual journeys take travelers away from the chaos of daily life into a realm of peace and self-discovery. Whether it’s visiting ancient temples, joining yoga and meditation retreats, or exploring sacred sites, spiritual tourism helps rejuvenate the mind and body. These destinations offer a chance to connect with oneself and experience inner",
    image: "/image/Spiritual.jpg",
    price: "99,999",
  },
  {
    id: 9,
    name: "Sri-Lanka",
    info: "Sri Lanka is a gem in the Indian Ocean, famous for its golden beaches, lush tea plantations, and ancient ruins. From wildlife safaris in Yala National Park to exploring UNESCO World Heritage sites like Sigiriya, it offers a diverse experience. The island’s warm hospitality and cultural richness make it a paradise for travelers.",
    image: "/image/Sri-Lanka.jpg",
    price: "99,999",
  },
  {
    id: 10,
    name: "Thailand",
    info: "Thailand is one of the most popular destinations in Asia, known for its tropical beaches, Buddhist temples, floating markets, and vibrant nightlife. Visitors enjoy exploring Bangkok’s bustling streets, Chiang Mai’s spiritual side, and Phuket’s stunning islands. With delicious street food and friendly locals, Thailand offers a colorful and unforgettable experience.",
    image: "/image/thailand.jpg",
    price: "99,999",
  },
  {
    id: 11,
    name: "Vietnam",
    info: "Vietnam is a country of breathtaking landscapes and rich heritage. From the majestic Ha Long Bay and terraced rice fields of Sapa to bustling cities like Hanoi and Ho Chi Minh, it combines natural beauty with culture. Street markets, ancient temples, and delicious cuisine make Vietnam a truly immersive destination for all types of travelers.",
    image: "/image/Vietnam.jpg",
    price: "99,999",
  },
];
export default Data;
